TARGET=p0-001

$(TARGET).zip: files.txt $(TARGET).cmp $(TARGET).gpi $(TARGET).plc $(TARGET).sol $(TARGET).stc $(TARGET).sts $(TARGET).out $(TARGET).dri $(TARGET).drd
	zip $@ $+

all: $(TARGET).zip

clean:
	rm -f $(TARGET).2l $(TARGET).3l $(TARGET).GBL $(TARGET).GBO $(TARGET).GBP $(TARGET).GBS $(TARGET).GML $(TARGET).GTL $(TARGET).GTO $(TARGET).GTP $(TARGET).GTS $(TARGET).TXT $(TARGET).cmp $(TARGET).drd $(TARGET).dri $(TARGET).gpi $(TARGET).out $(TARGET).plc $(TARGET).pls $(TARGET).pro $(TARGET).sol $(TARGET).stc $(TARGET).sts $(TARGET).b#? $(TARGET).s#?
